# Generated by Django 5.2.11 on 2026-02-14 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=50)),
                ("product_name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=20)),
                ("season", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("launch_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="inventory.company",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
                "unique_together": {("company", "sku")},
            },
        ),
        migrations.CreateModel(
            name="InventoryLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_stock", models.IntegerField(default=0)),
                ("warehouse_location", models.CharField(max_length=50)),
                ("last_restock_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_levels",
            },
        ),
        migrations.CreateModel(
            name="RiskAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "High Risk"),
                            ("medium", "Medium Risk"),
                            ("low", "Low Risk"),
                        ],
                        max_length=10,
                    ),
                ),
                ("overstock_risk_pct", models.FloatField()),
                (
                    "velocity",
                    models.CharField(
                        choices=[
                            ("fast", "Fast Mover"),
                            ("medium", "Medium Mover"),
                            ("slow", "Slow Mover"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recommended_action", models.TextField()),
                ("urgency", models.CharField(max_length=10)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_alerts",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "risk_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="inventory.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("predicted_units", models.FloatField()),
                ("lower_bound", models.FloatField()),
                ("upper_bound", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "predictions",
                "ordering": ["-created_at", "forecast_date"],
                "unique_together": {("product", "forecast_date", "created_at")},
            },
        ),
        migrations.CreateModel(
            name="SalesHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("units_sold", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "sales_history",
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
    ]
