# Generated by Django 5.2.11 on 2026-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={},
        ),
        migrations.RemoveField(
            model_name="company",
            name="is_active",
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="subscription_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("past_due", "Past Due"),
                    ("trialing", "Trialing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="company",
            table=None,
        ),
    ]
